name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-update
      run: sudo apt update
    - name: prepare
      run: sudo apt install python3 python3-yaml libelf-dev libbpf-dev linux-headers-`uname -r` clang llvm gcc linux-tools-`uname -r` linux-tools-generic -y
    - name: make
      run: make all

  build-legacy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-update
      run: sudo apt update
    - name: prepare
      run: sudo apt install python3 python3-yaml libelf-dev libbpf-dev linux-headers-`uname -r` clang llvm gcc linux-tools-`uname -r` linux-tools-generic -y
    - name: make
      run: make COMPAT=1 all

